# ===== Application =====
spring.application.name=gym-crm-system
spring.profiles.active=dev

# ===== JPA / Hibernate (common) =====
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ===== Jackson =====
spring.jackson.serialization.write-dates-as-timestamps=false

# ===== Storage =====
storage.trainees.file=trainees.csv
storage.trainers.file=trainers.csv
storage.trainings.file=trainings.csv

# ===== Security =====
security.password.length=10

# ===== Actuator (Крок 6) + Prometheus (Крок 7) =====
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true

# ===== Info endpoint =====
info.app.name=Gym CRM System
info.app.version=1.0.0